### ISSUE TITLE
org-roam templates

### ISSUE THREAD

**Issue by iamkarlson** [hlissner/doom-emacs-private#2]
### What would you like to know?

I'm new to org-roam. I'm looking for code examples and inspiration, and your config seems to be mature enough. Could you please post your org-roam templates somewhere please?

**Comment by edmundmiller** [comment]
https://github.com/hlissner/.doom.d/blob/master/autoload/org-roam.el

**Comment by iamkarlson** [comment]
I was talking about these:
```
(format "#+title: ${title}\n%%[%s/template/note.org]" org-roam-directory)
```

**Comment by yonghuier** [comment]
I also want it！If you could provide the org-roam-directory/template/*.org template files, I would be extremely grateful.

**Comment by hlissner** [comment]
There's not much to them, but [here they are](https://gist.github.com/hlissner/9243638c98d22b55595d4890f0cfddc2).

Unfortunately, the real meat is hidden in an unreleased and **highly** opinionated elisp library that manages my convoluted CRM and notetaking systems, all built over org-roam and closely coupled to my [beancount](https://github.com/beancount/beancount) ledgers. It'd need a gargantuan effort to separate personal data from it before it can be shared, which won't likely happen anytime soon.

**Comment by iamkarlson** [comment]
Thanks!
